use_frameworks!

target 'polkadot_Example' do
  pod 'polkadot', :path => '../'

  target 'polkadot_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
